version: '3.4'

services:
  recruiting_api:
    image: ${DOCKER_REGISTRY-}recruitingapi
    ports:
      - "40123:80"
    build:
      context: .
      dockerfile: Recruiting_API/Dockerfile


  onboarding_api:
    image: ${DOCKER_REGISTRY-}onboardingapi
    ports:
      - "40124:80"
    build:
      context: .
      dockerfile: Onboarding_API/Dockerfile


  authentication_api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    ports:
      - "40125:80"
    build:
      context: .
      dockerfile: Authentication_API/Dockerfile


  interview_api:
    image: ${DOCKER_REGISTRY-}interviewapi
    ports:
      - "40126:80"
    build:
      context: .
      dockerfile: Interview_API/Dockerfile

